### ISSUE TITLE
Why do we need redux-starter-kit in deps?

### ISSUE THREAD

**Issue by rlesniak** [thebrodmann/deox#40]
As in topic. Why? Is that necessary? 

PS. Really helpful lib, keep coding :)

**Comment by thebrodmann** [comment]
Hi @rlesniak 

As described in #9 since v1.3.0 Deox has another utility function to help developers to configure the store in a more elegant way. The idea of redux-starter-kit in `configureStore` function is neat and for now, I don't think there should be any difference between Deox and redux starter-kit in the implementation of `configureStore` function. So Deox just re-exports `configureStore` from redux-starter-kit.
