### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by eXaminator** [thebrodmann/deox#43]
Hi,

great library, but the bundle footprint seems to be rather large. In fact, in my small app it's the second largest after react-dom, even larger than redux itself.

webpack-bundle-analyzer gives me the following non-gzipped values:
react-dom: 103.89KB
redux: 6.04KB
deox: 40.09KB

I saw issue #42 which was just resolved. Maybe this will fix this issue too, but in general I'm not sure if maybe this library could be optimised some more. Maybe even add better support for tree-shaking. Sadly I'm not an expert on that topic myself.

**Comment by thebrodmann** [comment]
Hi @eXaminator 

Deox internally supports tree-shaking. In the build system of Deox, we create an ESM bundle of Deox that is tree-shakable. The problem is the `browser` field in the package.json. Webpack prefers `browser` field over `module` and thus follow non-tree-shakable UMD bundle instead tree-shakable ESM bundle.

**Comment by thebrodmann** [comment]
To solve the problem we should rename `browser` field to `unpkg`.

**Comment by thebrodmann** [comment]
![Screen Shot 2019-04-05 at 10 50 33 PM](https://user-images.githubusercontent.com/20781126/55648570-e6a9c300-57f5-11e9-96f9-65a1e0621ba9.png)
